# Generated by Django 3.2.8 on 2022-01-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_edit',
            field=models.BooleanField(default=False),
        ),
    ]
